name: ${project.artifactId}
version: ${project.version}

main: com.iridium.iridiumskyblock.IridiumSkyblock
api-version: '1.13'

author: Peaches_MLG
description: Skyblock Redefined

depend: [Vault]
softdepend:
  - "MVdWPlaceholderAPI"
  - "PlaceholderAPI"
  - "Essentials"
  - "EssentialsSpawn"
  - "RoseStacker"
  - "WorldEdit"
  - "WorldGuard"
loadbefore:
  - "Multiverse-Core"

commands:
  iridiumskyblock:
    aliases: [ "island", is ]
    description: Main plugin command
